server.port: 8080

spring.rabbitmq:
  listener.simple.concurrency: 5
  username: guest
  password: guest
  host: localhost

messaging:
  exchange: spring-cloud-example
  queues:
    get: cat-service-get
    send: cat-service-send
  routing-key: cat-event
