spring.application.name: auth
server.port: 0
eureka.client.service-url.default-zone: http://localhost:8761/eureka


spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: lolxaxlol