spring.application.name: user
eureka.client.service-url.defaultZone: http://registry:8761/eureka

spring.rabbitmq:
  listener.concurrency: 5
  username: guest
  password: guest
  host: rabbit

spring:
  datasource:
    url: jdbc:postgresql://db:5432/test
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis

messaging:
  exchange: spring-cloud-example
  user:
    queue: user-service
    routing-key: user-event
