spring.application.name: user

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

spring.rabbitmq:
  listener.concurrency: 5
  username: guest
  password: guest
  host: localhost

spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: lolxaxlol

messaging:
  exchange: spring-cloud-example
  user:
    queue: user-service
    routing-key: user-event

spring:
  jpa:
    hibernate:
      ddl-auto: update

server.port: 0