spring.application.name: user

eureka.client.service-url.defaultZone: http://localhost:8761/eureka

spring.rabbitmq:
  listener.concurrency: 5
  username: guest
  password: guest
  host: localhost

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: lolxaxlol
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000


messaging:
  exchange: spring-cloud-example
  user:
    queue: user-service
    routing-key: user-event

server.port: 0