spring.application.name: zuul-gateway

zuul:
  prefix: /api
  ignoredServices: "*"
  routes:
    user:
      path: /users/**
      serviceId: user

eureka:
  client:
    service-url.defaultZone: http://registry:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
server:
  port: 8090
