spring.application.name: zuul-gateway

zuul:
  prefix: /api
  ignoredServices: "*"
  routes:
    user:
      path: /users/**
      serviceId: user

eureka:
  client:
    service-url.defaultZone: http://registry:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000
server:
  port: 8090

zuul.routes.auth-service:
  path: /auth/**
  service-id: auth

  # By default, all requests to gallery service for example will start with: "/gallery/"
  # What will be sent to the gallery service is what comes after the path defined,
  # So, if request is "/gallery/view/1", gallery service will get "/view/1".
  # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
  strip-prefix: false
  # Exclude authorization from sensitive headers
  sensitive-headers: Cookie,Set-Cookie